spring:
  application:
    name: click-api
  datasource:
    url: jdbc:postgresql://localhost:5432/ad_events
    username: adtech
    password: adtech
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
        queue-not-found-strategy: create

server:
  port: 8080
